import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer';
import { SamrtFitProvider } from '@/context/smartfitContext';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Smartfit desafio frontend',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <SamrtFitProvider>
          <Header />
          {children}
          <Footer />
        </SamrtFitProvider>
      </body>
    </html>
  )
}
